- name: Install thunderbird
  become: true
  dnf:
    name: thunderbird
    state: latest

- name: Generate profile directory
  shell: "DISPLAY=:0 thunderbird -CreateProfile {{ username }}"

- name: Get themes directory
  shell: "ls /home/{{ username }}/.thunderbird/ | grep {{ username }}"
  register: thunderbird_themes_dir

- name: Clone Monterail
  git:
    repo: git@github.com:spymastermatt/thunderbird-monterail.git
    dest: "/home/{{ username }}/.thunderbird/{{ thunderbird_themes_dir.stdout }}/chrome"
    accept_hostkey: yes
    force: yes

- name: Set Monterail theme
  copy:
    src: "/home/{{ username }}/.thunderbird/{{ thunderbird_themes_dir.stdout }}/chrome/themes/monterail.css"
    dest: "/home/{{ username }}/.thunderbird/{{ thunderbird_themes_dir.stdout }}/chrome/userChrome.css"