# ansible-playbook -K playbook_enconn.yml --tags server -i hosts -u amarok
# ansible-playbook -K playbook_enconn.yml --tags update_server -i hosts -u amarok
---

- name: Configure server
  hosts: server
  vars:
    - username: AmarOk
    - hostname: enconn.fr
    - lets_encrypt_mail: contact@enconn.fr
    - ansible_ssh_private_key_file: "/home/AmarOk/.ssh/enconn.fr"
  roles:
    - info
    - software
    - blog
    - data