# ansible-playbook -K playbook_enconn.yml --tags server -i hosts -u amarok
# ansible-playbook -K playbook_enconn.yml --tags update_server -i hosts -u amarok
---

- name: Configure server
  hosts: server
  vars:
    - username: AmarOk
    - hostname: enconn.fr
  roles:
    #- info
    - software
    - blog
    #- role: geerlingguy.nginx
    #  tags:
    #    - server
    #    - server_specific
    #  become: true
    #  nginx_vhosts:
    #    - listen: "443 ssl http2"
    #      server_name: "enconn.fr"
    #      server_name_redirect: "www.enconn.fr"
    #      root: "/var/www/enconn"
    #      index: "index.php index.html index.htm"
    #      error_page: "404.html"
    #      extra_parameters: |
    #        location ~ \.php$ {
    #            fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #            fastcgi_pass unix:/var/run/php5-fpm.sock;
    #            fastcgi_index index.php;
    #            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #            include fastcgi_params;
    #        }
    #        ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
    #        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    #        ssl_protocols       TLSv1.1 TLSv1.2;
    #        ssl_ciphers         HIGH:!aNULL:!MD5;
    #- cron # livedns, update website
    # Change hosts