- name: Install certbot
  become: true
  dnf:
    name: certbot
    state: latest

- name: Install certbot-nginx
  become: true
  dnf:
    name: certbot-nginx
    state: latest

- name: Generate certificate for enconn.fr
  become: true
  command: "certbot --nginx -m {{ lets_encrypt_mail }} --agree-tos --no-eff-email --redirect -d {{ hostname }}"

- name: Generate certificate for media.enconn.fr
  become: true
  command: "certbot --nginx -m {{ lets_encrypt_mail }} --agree-tos --no-eff-email --redirect -d media.enconn.fr"

- name: Generate certificate for code.enconn.fr
  become: true
  command: "certbot --nginx -m {{ lets_encrypt_mail }} --agree-tos --no-eff-email --redirect -d code.enconn.fr"

- name: Add cron to update certificate
  become: true
  cron:
    name: "Update certificate"
    user: "root"
    minute: "0"
    hour: "0,12"
    job: "certbot renew"

- name: Restart nginx
  become: true
  systemd:
    name: nginx
    state: restarted