- name: Copy .htpasswd for media.enconn.fr
  become: true
  copy:
    remote_src: yes
    src: "/tmp/decrypted_lutices/media.enconn.fr/.htpasswd"
    dest: "/home/{{ username }}/media.enconn.fr/.htpasswd"
    mode: '0644'

- name: Embrace SE Linux fun for media
  command: chcon -R -t httpd_sys_content_t /media/media_drive/

- name: Embrace SE Linux fun for htpasswd
  command: chcon -R -t httpd_sys_content_t /home/{{ username }}/media.enconn.fr

- name: Generate certificate
  become: true
  command: "certbot --nginx -m {{ lets_encrypt_mail }} --agree-tos --no-eff-email --redirect -d media.enconn.fr"
