- name: Prepare Jellyfin environment
  become: true
  shell: | # TODO clean
    docker pull jellyfin/jellyfin
    mkdir -p /var/lib/jellyfin
    chown -R amarok:nginx /var/lib/jellyfin
    mkdir -p /etc/jellyfin
    chown -R amarok:nginx /etc/jellyfin
    mkdir -p /home/amarok/.cache/jellyfin
    chown -R amarok:nginx /home/amarok/.cache/jellyfin
    mkdir -p /media/jellyfin
    chown -R amarok:nginx /media/jellyfin
    mkdir -p /opt/jellyfin
    chown -R amarok:nginx /opt/jellyfin

- name: Copy jellyfin config
  copy:
    src: .config/jellyfin/docker-compose.yml
    dest: "/opt/jellyfin/docker-compose.yml"
    mode: '0644'

- name: Start Jellyfin
  become: true
  shell:
    cmd: docker-compose up -d
    chdir: /opt/jellyfin