- name: Create /home/{{ username }}/Projects
  file:
      path: /home/{{ username }}/Projects
      state: directory

- name: Clone OpenDHT
  git:
    repo: git@github.com:savoirfairelinux/opendht.git
    dest: "/home/{{ username }}/Projects/opendht"
    accept_hostkey: yes
    force: yes
    track_submodules: yes
    recursive: yes

# TODO move to .cqfd

- name: Install dependencies
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items: [readline-devel, gnutls-devel, msgpack-devel, python3-Cython, python3-devel, redhat-rpm-config]

- name: Create /home/{{ username }}/Projects/opendht/build
  file:
      path: /home/{{ username }}/Projects/opendht/build
      state: directory

- name: Build OpenDHT
  shell:
    cmd: |
      cmake -DOPENDHT_PYTHON=ON -DOPENDHT_TOOLS=ON ..
      make -j9
    chdir: /home/{{ username }}/Projects/opendht/build
